name: Laravel

on:
  push:
    branches: [ "main" ]
 

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get composer cache directory
      id: composer_config
      uses: baschny/php-composer-action@v1
      with:
        composer_version: ${{ env.COMPOSER_VERSION }}
        command: get_config

    - name: Cache composer downloads
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer_config.outputs.composer_cache_dir }}
        key: composer-v${{ steps.composer_config.outputs.composer_major_version }}

    - name: Run composer install
      uses: baschny/php-composer-action@v1
      with:

        command: install

      run: composer install
    - name: Actualiza composer cambios
      run: composer update
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit